### ISSUE TITLE
ElasticSearchin päivitys

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/Koha-23x#100]
### Siirrettävä ominaisuus

ElasticSearch 6 version tuki loppuu 23.11 myötä, täytyy päivittää 7 tai 8 versioon.

**Comment by lmstrand** [comment]
8.11.1-versio vaati konfigurointia (ainakin dev-ympäristössä dockeroituna):

    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

Ilman  xpack.security.enabled=false:

[Elasticsearch showing received plaintext http traffic on an https channel in console](https://stackoverflow.com/questions/71492404/elasticsearch-showing-received-plaintext-http-traffic-on-an-https-channel-in-con)

As of ES 8, SSL/TLS is ON by default for HTTP clients.

The WARN message says

http client did not trust this server's certificate

... which means that you need to tell your browser to trust the server certificate. it is self-signed by default, so that's probably the reason.

Or you can simply disable SSL in your elasticsearch.yml configuration, that would also work.

Ilman discovery.type=single-node:

[ElasticSearch start up error - the default discovery settings are unsuitable for production use;](https://stackoverflow.com/questions/59350069/elasticsearch-start-up-error-the-default-discovery-settings-are-unsuitable-for)

In short, if you are running Elasticsearch locally(single node) or just with a single node on the cloud then just use below config in your elasticsearch.yml to avoid the production check, and to make it work, more info about this config in [this SO](https://stackoverflow.com/a/60426167/4039431) answer:

**Comment by lmstrand** [comment]
Outi-Nextille asennettu Elasticsearchin versio 8.11.1 ja päivitetty saman version icu-analysis plugin, josta heitti herjaa kun oli vanhalle versiolle.

Jotta indeksointi-cron lähti tulille, piti elasticsearch.yaml:iin lisätä seuraavat:

xpack.security.enabled: false   <--- korjasi herjan missing authentication credentials for REST request
xpack.security.enrollment.enabled: false <--- laitoin extrana, ei varmaan tarvita

discovery.type: single-node <--- En ymmärrä:

https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#single-node-discovery

**Comment by lmstrand** [comment]
Lisätty myös:

ExecStartPre=/usr/local/bin/elastictmpfs start
ExecStop=/usr/local/bin/elastictmpfs stop

systemd-unitiin (elasticsearch.service) ja tehty nexteillä systemctl daemon-reload

**Comment by CodoDerDritte** [comment]
- Vaatii uudelleenindeksoinnit versiopäivityksessä, koska vanhan ElasticSearch-version indeksejä ei voi muuttaa yhteensopivaksi uuden version kanssa (vanhat indeksit on hävitetty nexteiltä).
- ElasticSearchin versio täytyy lukita, koska icu-plugin vaatii aina tarkalleen tietyn version ElasticSearchista. Muussa tapauksessa ElasticSearch "hajoaa" joka kerta kun konttiin asennetaan käyttöjärjestelmäpäivitykset.

**Comment by CodoDerDritte** [comment]
Kontainerien sisällä kernel raportoi vapaan muistin määrän väärin. Käytettynä näkyy ainoastaan kyseisen kontainerin käyttämä muisti. Loppu näkyy vapaana, vaikka olisi toisten kontainerien käytössä. Elasticsearch varaa käynnistyessään muistia perustuen vapaan muistin määrään järjestelmässä, joka siis tässä tapauksessa on raportoitu väärin ja johtaa muistin loppumiseen kesken ja Elasticsearchin kaatuiluun sen vuoksi (tai voi se johtaa kamalampiinkin asioihin, mutta ei mennä niihin).

Ongelma täytyy korjata JVM:n heapsize konfiguraatiota muuttamalla. Nextien konfiguraatiotiedostoissa /etc/elasticsearch/jvm.options.d/kohasuomi.options on toimiva (mutta ei varmaankaan optimaalinen) konfiguraatio. Tiedosto sisältää kaksi määritystä liittyen heap sizeihin:

```
-Xms4g
-Xmx4g
```
Tuo 4g on ehkä aika vähän, mutta tarvii tavata dokumentaatioo vielä tuon osalta. Mennään nyt hetken aikaa tällä.

**Comment by AnneliO** [comment]
Paketinhallinasta pitää jäädyttää versio.

**Comment by CodoDerDritte** [comment]
Elasticsearchin versio on jäädytetty. Jos jäädytys on tarpeen purkaa:

```
echo "elasticsearch install" | sudo dpkg --set-selections
```
